name: Terraform flow

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIAZOTNZJQYMDQ5NVD2
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }} 

      - name: Resource terraform
        run: |
          cd terraform
          terraform init
          terraform validate
          terraform plan

      - name: Applying changes
        run: |
          cd terraform
          terraform apply
